// <auto-generated />
namespace SocialNetworkWorkShop.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Addedbetterconnectionsbetweenpostsandusers : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addedbetterconnectionsbetweenpostsandusers));
        
        string IMigrationMetadata.Id
        {
            get { return "201803131201164_Added better connections between posts and users"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
